import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/ui/Header";
import PageTransition from "@/components/PageTransition";
import StairEffect from "@/components/StairEffect";

const JetBrainsMono = JetBrains_Mono({
  weights:["100","200","300","400","500","600","700","800","900"],
  variable: "--font-jetbrainsmono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${JetBrainsMono.variable}`}
      >
        <Header></Header> 
        <PageTransition>
        <StairEffect/>
        {children}
        </PageTransition>
      </body>
    </html>
  );
}
